//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSC.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSC.App_GlobalResources.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 特批密码 的本地化字符串。
        /// </summary>
        public static string AuthPwd {
            get {
                return ResourceManager.GetString("AuthPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进入 的本地化字符串。
        /// </summary>
        public static string BtnEnterText {
            get {
                return ResourceManager.GetString("BtnEnterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string BtnLoginText {
            get {
                return ResourceManager.GetString("BtnLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司用户不允许修改系统管理员的特批密码 的本地化字符串。
        /// </summary>
        public static string CancelModifyAuthPwd {
            get {
                return ResourceManager.GetString("CancelModifyAuthPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司用户不允许修改系统管理员的登录密码 的本地化字符串。
        /// </summary>
        public static string CancelModifyLogPwd {
            get {
                return ResourceManager.GetString("CancelModifyLogPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dah Chong Hong HK Ltd 的本地化字符串。
        /// </summary>
        public static string ComanyName {
            get {
                return ResourceManager.GetString("ComanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入确认新密码 的本地化字符串。
        /// </summary>
        public static string EnterConfirmPassword {
            get {
                return ResourceManager.GetString("EnterConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入新密码 的本地化字符串。
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录密码 的本地化字符串。
        /// </summary>
        public static string LoginPwd {
            get {
                return ResourceManager.GetString("LoginPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 CSC 系统 的本地化字符串。
        /// </summary>
        public static string LoginToCSCText {
            get {
                return ResourceManager.GetString("LoginToCSCText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改特批密码成功 的本地化字符串。
        /// </summary>
        public static string ModifyAuthPwdSuccess {
            get {
                return ResourceManager.GetString("ModifyAuthPwdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改登录密码成功 的本地化字符串。
        /// </summary>
        public static string ModifyLoginPwdSuccess {
            get {
                return ResourceManager.GetString("ModifyLoginPwdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        public static string ModifyPassword {
            get {
                return ResourceManager.GetString("ModifyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新确认密码 的本地化字符串。
        /// </summary>
        public static string NewConfirmPassword {
            get {
                return ResourceManager.GetString("NewConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码 的本地化字符串。
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码和确认新密码不一致, 请重新输入. 的本地化字符串。
        /// </summary>
        public static string PassNoEqualsConfirmPass {
            get {
                return ResourceManager.GetString("PassNoEqualsConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码： 的本地化字符串。
        /// </summary>
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (密码位数最少需要三位，密码不区分大小写) 的本地化字符串。
        /// </summary>
        public static string PasswordValidate {
            get {
                return ResourceManager.GetString("PasswordValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户密码将于 {0} 过期,请及时修改密码. 的本地化字符串。
        /// </summary>
        public static string PasswordWarning {
            get {
                return ResourceManager.GetString("PasswordWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        public static string PleaseSelectShop {
            get {
                return ResourceManager.GetString("PleaseSelectShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择店 的本地化字符串。
        /// </summary>
        public static string SelectShopText {
            get {
                return ResourceManager.GetString("SelectShopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 店： 的本地化字符串。
        /// </summary>
        public static string ShopText {
            get {
                return ResourceManager.GetString("ShopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transaction Date: 的本地化字符串。
        /// </summary>
        public static string TransactionDate {
            get {
                return ResourceManager.GetString("TransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户号： 的本地化字符串。
        /// </summary>
        public static string UserCode {
            get {
                return ResourceManager.GetString("UserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已被锁定 的本地化字符串。
        /// </summary>
        public static string UserIsLocked {
            get {
                return ResourceManager.GetString("UserIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本用户账号已在 {0} 机器登录，禁止二次登录。 的本地化字符串。
        /// </summary>
        public static string UserLoginedIPFormat {
            get {
                return ResourceManager.GetString("UserLoginedIPFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该用户已经在IP:{0}上登录了 的本地化字符串。
        /// </summary>
        public static string UserLoginOtherIpFormat {
            get {
                return ResourceManager.GetString("UserLoginOtherIpFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名称： 的本地化字符串。
        /// </summary>
        public static string UserNameDsc {
            get {
                return ResourceManager.GetString("UserNameDsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户： 的本地化字符串。
        /// </summary>
        public static string UserNameText {
            get {
                return ResourceManager.GetString("UserNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前用户不存在。 的本地化字符串。
        /// </summary>
        public static string UserNoExists {
            get {
                return ResourceManager.GetString("UserNoExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不属于当前店，不能修改此用户的特批密码. 的本地化字符串。
        /// </summary>
        public static string UserNoExists_Auth {
            get {
                return ResourceManager.GetString("UserNoExists_Auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不属于当前店，不能修改此用户的登录密码。 的本地化字符串。
        /// </summary>
        public static string UserNoExists_Log {
            get {
                return ResourceManager.GetString("UserNoExists_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本号： 的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
