//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessResultMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessResultMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSC.App_GlobalResources.BusinessResultMessage", typeof(BusinessResultMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消失败.
        /// </summary>
        public static string INF_CANCEL_FAILED {
            get {
                return ResourceManager.GetString("INF_CANCEL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel ID/OD Order Failed..
        /// </summary>
        public static string INF_CANCEL_IDOD_ORDER_FAILED {
            get {
                return ResourceManager.GetString("INF_CANCEL_IDOD_ORDER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel ID/OD Order Succeed..
        /// </summary>
        public static string INF_CANCEL_IDOD_ORDER_SUCCEED {
            get {
                return ResourceManager.GetString("INF_CANCEL_IDOD_ORDER_SUCCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Job Failed..
        /// </summary>
        public static string INF_CANCEL_JOB_FAILED {
            get {
                return ResourceManager.GetString("INF_CANCEL_JOB_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Job Succeed..
        /// </summary>
        public static string INF_CANCEL_JOB_SUCCEED {
            get {
                return ResourceManager.GetString("INF_CANCEL_JOB_SUCCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消成功.
        /// </summary>
        public static string INF_CANCEL_SUCCEED {
            get {
                return ResourceManager.GetString("INF_CANCEL_SUCCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消选用失败。.
        /// </summary>
        public static string INF_CANCELSELECT_FAILED {
            get {
                return ResourceManager.GetString("INF_CANCELSELECT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消选用成功。.
        /// </summary>
        public static string INF_CANCELSELECT_SUCCEED {
            get {
                return ResourceManager.GetString("INF_CANCELSELECT_SUCCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Failed..
        /// </summary>
        public static string INF_CONFIRM_FAILED {
            get {
                return ResourceManager.GetString("INF_CONFIRM_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Succeed..
        /// </summary>
        public static string INF_CONFIRM_SUCCEED {
            get {
                return ResourceManager.GetString("INF_CONFIRM_SUCCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制失败。.
        /// </summary>
        public static string INF_COPY_FAILED {
            get {
                return ResourceManager.GetString("INF_COPY_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制成功。.
        /// </summary>
        public static string INF_COPY_SUCCEED {
            get {
                return ResourceManager.GetString("INF_COPY_SUCCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败。.
        /// </summary>
        public static string INF_DELETE_FAILED {
            get {
                return ResourceManager.GetString("INF_DELETE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除成功。.
        /// </summary>
        public static string INF_DELETE_SUCCEED {
            get {
                return ResourceManager.GetString("INF_DELETE_SUCCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operate failed..
        /// </summary>
        public static string INF_OPERATE_FAILED {
            get {
                return ResourceManager.GetString("INF_OPERATE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operate succeed..
        /// </summary>
        public static string INF_OPERATE_SUCCEED {
            get {
                return ResourceManager.GetString("INF_OPERATE_SUCCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存失败。.
        /// </summary>
        public static string INF_SAVE_FAILED {
            get {
                return ResourceManager.GetString("INF_SAVE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存成功。.
        /// </summary>
        public static string INF_SAVE_SUCCEED {
            get {
                return ResourceManager.GetString("INF_SAVE_SUCCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选用失败。.
        /// </summary>
        public static string INF_SELECT_FAILED {
            get {
                return ResourceManager.GetString("INF_SELECT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选用成功。.
        /// </summary>
        public static string INF_SELECT_SUCCEED {
            get {
                return ResourceManager.GetString("INF_SELECT_SUCCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置失败。.
        /// </summary>
        public static string INF_SET_FAILED {
            get {
                return ResourceManager.GetString("INF_SET_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置成功。.
        /// </summary>
        public static string INF_SET_SUCCEED {
            get {
                return ResourceManager.GetString("INF_SET_SUCCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存在相同记录。.
        /// </summary>
        public static string MSG_1001 {
            get {
                return ResourceManager.GetString("MSG_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记录不存在。.
        /// </summary>
        public static string MSG_1002 {
            get {
                return ResourceManager.GetString("MSG_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该记录已被其他用户修改。.
        /// </summary>
        public static string MSG_1003 {
            get {
                return ResourceManager.GetString("MSG_1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此记录已被其他记录使用，不能删除此记录。.
        /// </summary>
        public static string MSG_1004 {
            get {
                return ResourceManager.GetString("MSG_1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此记录已被其他记录使用，不能操作此记录。.
        /// </summary>
        public static string MSG_1005 {
            get {
                return ResourceManager.GetString("MSG_1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts contains substitution parts can not change Master Parts value..
        /// </summary>
        public static string MSG_1006 {
            get {
                return ResourceManager.GetString("MSG_1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts has been referenced by substitution parts can not change Master Parts value..
        /// </summary>
        public static string MSG_1007 {
            get {
                return ResourceManager.GetString("MSG_1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code has been duplicated,please change it..
        /// </summary>
        public static string MSG_1008 {
            get {
                return ResourceManager.GetString("MSG_1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rate of date time has error,please check it..
        /// </summary>
        public static string MSG_1009 {
            get {
                return ResourceManager.GetString("MSG_1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group No. has been used by other Products already!.
        /// </summary>
        public static string MSG_1010 {
            get {
                return ResourceManager.GetString("MSG_1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job No. is not exists.
        /// </summary>
        public static string MSG_1011 {
            get {
                return ResourceManager.GetString("MSG_1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists Normal state Job Adjustment.
        /// </summary>
        public static string MSG_1012 {
            get {
                return ResourceManager.GetString("MSG_1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Job Adjustment data has been confirmed,Can not delete it..
        /// </summary>
        public static string MSG_1013 {
            get {
                return ResourceManager.GetString("MSG_1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Job Adjustment data has been confirmed,Can not confrim it again..
        /// </summary>
        public static string MSG_1014 {
            get {
                return ResourceManager.GetString("MSG_1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Job Order has not complete,can not create Job Adjustment..
        /// </summary>
        public static string MSG_1015 {
            get {
                return ResourceManager.GetString("MSG_1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Normal state of Job Order already exists, you can&apos;t create a new Job Order..
        /// </summary>
        public static string MSG_1016 {
            get {
                return ResourceManager.GetString("MSG_1016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists valid ID/OD Order.
        /// </summary>
        public static string MSG_1017 {
            get {
                return ResourceManager.GetString("MSG_1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID/OD Order has been cancelled,Can not canel it again..
        /// </summary>
        public static string MSG_1018 {
            get {
                return ResourceManager.GetString("MSG_1018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer product is not exists..
        /// </summary>
        public static string MSG_1019 {
            get {
                return ResourceManager.GetString("MSG_1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty greater Technician Available Qty, pls. check the qty is entered correctly..
        /// </summary>
        public static string MSG_1020 {
            get {
                return ResourceManager.GetString("MSG_1020", resourceCulture);
            }
        }
    }
}
