//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSC.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalText() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSC.App_GlobalResources.GlobalText", typeof(GlobalText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载…… 的本地化字符串。
        /// </summary>
        public static string AjaxProcess {
            get {
                return ResourceManager.GetString("AjaxProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approve 的本地化字符串。
        /// </summary>
        public static string BtnApprove {
            get {
                return ResourceManager.GetString("BtnApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audit 的本地化字符串。
        /// </summary>
        public static string BtnAudit {
            get {
                return ResourceManager.GetString("BtnAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audit 的本地化字符串。
        /// </summary>
        public static string BtnAuditText {
            get {
                return ResourceManager.GetString("BtnAuditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string BtnBack {
            get {
                return ResourceManager.GetString("BtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Booked Job 的本地化字符串。
        /// </summary>
        public static string BtnBookedJob {
            get {
                return ResourceManager.GetString("BtnBookedJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Book History 的本地化字符串。
        /// </summary>
        public static string BtnBookHistory {
            get {
                return ResourceManager.GetString("BtnBookHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Booking History 的本地化字符串。
        /// </summary>
        public static string BtnBookingHistory {
            get {
                return ResourceManager.GetString("BtnBookingHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Booking List 的本地化字符串。
        /// </summary>
        public static string BtnBookingList {
            get {
                return ResourceManager.GetString("BtnBookingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部取消选用 的本地化字符串。
        /// </summary>
        public static string BtnCancelAllSelectedText {
            get {
                return ResourceManager.GetString("BtnCancelAllSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Booking 的本地化字符串。
        /// </summary>
        public static string BtnCancelBooking {
            get {
                return ResourceManager.GetString("BtnCancelBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Job 的本地化字符串。
        /// </summary>
        public static string BtnCancelJob {
            get {
                return ResourceManager.GetString("BtnCancelJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消选用 的本地化字符串。
        /// </summary>
        public static string BtnCancelSelectedText {
            get {
                return ResourceManager.GetString("BtnCancelSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string btnCancelText {
            get {
                return ResourceManager.GetString("btnCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string BtnComplete {
            get {
                return ResourceManager.GetString("BtnComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定倒置 的本地化字符串。
        /// </summary>
        public static string BtnConfirmChange {
            get {
                return ResourceManager.GetString("BtnConfirmChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string BtnConfirmText {
            get {
                return ResourceManager.GetString("BtnConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string BtnCopy {
            get {
                return ResourceManager.GetString("BtnCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create By New Product 的本地化字符串。
        /// </summary>
        public static string BtnCreateByNewProdText {
            get {
                return ResourceManager.GetString("BtnCreateByNewProdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create By Product No. 的本地化字符串。
        /// </summary>
        public static string BtnCreateByProdNoText {
            get {
                return ResourceManager.GetString("BtnCreateByProdNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create From 的本地化字符串。
        /// </summary>
        public static string BtnCreateFromText {
            get {
                return ResourceManager.GetString("BtnCreateFromText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Job 的本地化字符串。
        /// </summary>
        public static string BtnCreateJob {
            get {
                return ResourceManager.GetString("BtnCreateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Job For ID/OD 的本地化字符串。
        /// </summary>
        public static string BtnCreateJobForIDOD {
            get {
                return ResourceManager.GetString("BtnCreateJobForIDOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        public static string BtnCreateText {
            get {
                return ResourceManager.GetString("BtnCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address Updated Info. 的本地化字符串。
        /// </summary>
        public static string BtnCustProdAddrUpdatedInfo {
            get {
                return ResourceManager.GetString("BtnCustProdAddrUpdatedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decline 的本地化字符串。
        /// </summary>
        public static string BtnDecline {
            get {
                return ResourceManager.GetString("BtnDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Job 的本地化字符串。
        /// </summary>
        public static string BtnDeleteJob {
            get {
                return ResourceManager.GetString("BtnDeleteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Product 的本地化字符串。
        /// </summary>
        public static string BtnDeleteProduct {
            get {
                return ResourceManager.GetString("BtnDeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string BtnDeleteText {
            get {
                return ResourceManager.GetString("BtnDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detail Result 的本地化字符串。
        /// </summary>
        public static string BtnDetailResult {
            get {
                return ResourceManager.GetString("BtnDetailResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载数据CSV 的本地化字符串。
        /// </summary>
        public static string BtnDownCSV {
            get {
                return ResourceManager.GetString("BtnDownCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载 的本地化字符串。
        /// </summary>
        public static string BtnDownload {
            get {
                return ResourceManager.GetString("BtnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载模版CSV 的本地化字符串。
        /// </summary>
        public static string BtnDownTempCSV {
            get {
                return ResourceManager.GetString("BtnDownTempCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Job 的本地化字符串。
        /// </summary>
        public static string BtnEditJob {
            get {
                return ResourceManager.GetString("BtnEditJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Mail Address 的本地化字符串。
        /// </summary>
        public static string BtnEditMailAddress {
            get {
                return ResourceManager.GetString("BtnEditMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string BtnEditText {
            get {
                return ResourceManager.GetString("BtnEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出数据 CSV 的本地化字符串。
        /// </summary>
        public static string BtnExportText {
            get {
                return ResourceManager.GetString("BtnExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate 的本地化字符串。
        /// </summary>
        public static string BtnGenerateText {
            get {
                return ResourceManager.GetString("BtnGenerateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group Product 的本地化字符串。
        /// </summary>
        public static string BtnGroupProduct {
            get {
                return ResourceManager.GetString("BtnGroupProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History 的本地化字符串。
        /// </summary>
        public static string BtnHistory {
            get {
                return ResourceManager.GetString("BtnHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 汇入 的本地化字符串。
        /// </summary>
        public static string BtnImport {
            get {
                return ResourceManager.GetString("BtnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string BtnModifyText {
            get {
                return ResourceManager.GetString("BtnModifyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string BtnNewText {
            get {
                return ResourceManager.GetString("BtnNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NO 的本地化字符串。
        /// </summary>
        public static string BtnNoText {
            get {
                return ResourceManager.GetString("BtnNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string BtnOKText {
            get {
                return ResourceManager.GetString("BtnOKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overwrite Mailing Address 的本地化字符串。
        /// </summary>
        public static string BtnOverwriteMailingAddressText {
            get {
                return ResourceManager.GetString("BtnOverwriteMailingAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print 的本地化字符串。
        /// </summary>
        public static string BtnPrint {
            get {
                return ResourceManager.GetString("BtnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quotation 的本地化字符串。
        /// </summary>
        public static string BtnQuotation {
            get {
                return ResourceManager.GetString("BtnQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拒绝 的本地化字符串。
        /// </summary>
        public static string BtnReject {
            get {
                return ResourceManager.GetString("BtnReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列印 的本地化字符串。
        /// </summary>
        public static string BtnReport {
            get {
                return ResourceManager.GetString("BtnReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string BtnReset {
            get {
                return ResourceManager.GetString("BtnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string BtnResetText {
            get {
                return ResourceManager.GetString("BtnResetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return 的本地化字符串。
        /// </summary>
        public static string BtnReturn {
            get {
                return ResourceManager.GetString("BtnReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转返 的本地化字符串。
        /// </summary>
        public static string BtnReturnChange {
            get {
                return ResourceManager.GetString("BtnReturnChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string BtnReturnText {
            get {
                return ResourceManager.GetString("BtnReturnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string BtnSaveText {
            get {
                return ResourceManager.GetString("BtnSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string BtnSearchText {
            get {
                return ResourceManager.GetString("BtnSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部选用 的本地化字符串。
        /// </summary>
        public static string BtnSelectedAllText {
            get {
                return ResourceManager.GetString("BtnSelectedAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选用 的本地化字符串。
        /// </summary>
        public static string BtnSelectedText {
            get {
                return ResourceManager.GetString("BtnSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string btnSetText {
            get {
                return ResourceManager.GetString("btnSetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本店选用 的本地化字符串。
        /// </summary>
        public static string BtnShopSelectedText {
            get {
                return ResourceManager.GetString("BtnShopSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        public static string BtnSignOutText {
            get {
                return ResourceManager.GetString("BtnSignOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        public static string BtnSubmit {
            get {
                return ResourceManager.GetString("BtnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        public static string BtnSubmitText {
            get {
                return ResourceManager.GetString("BtnSubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传数据CSV 的本地化字符串。
        /// </summary>
        public static string BtnUploadCSV {
            get {
                return ResourceManager.GetString("BtnUploadCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 核对 的本地化字符串。
        /// </summary>
        public static string BtnValid {
            get {
                return ResourceManager.GetString("BtnValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检视 的本地化字符串。
        /// </summary>
        public static string BtnViewText {
            get {
                return ResourceManager.GetString("BtnViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Void 的本地化字符串。
        /// </summary>
        public static string BtnVoid {
            get {
                return ResourceManager.GetString("BtnVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YES 的本地化字符串。
        /// </summary>
        public static string BtnYesText {
            get {
                return ResourceManager.GetString("BtnYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解除冻结 的本地化字符串。
        /// </summary>
        public static string CancelFrozen {
            get {
                return ResourceManager.GetString("CancelFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要解除冻结吗？ 的本地化字符串。
        /// </summary>
        public static string CancelFrozenConfirm {
            get {
                return ResourceManager.GetString("CancelFrozenConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解除冻结不成功 的本地化字符串。
        /// </summary>
        public static string CancelFrozenNoSuccess {
            get {
                return ResourceManager.GetString("CancelFrozenNoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解除冻结成功 的本地化字符串。
        /// </summary>
        public static string CancelFrozenSuccess {
            get {
                return ResourceManager.GetString("CancelFrozenSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to cancel this job? 的本地化字符串。
        /// </summary>
        public static string CancelJobConfirm {
            get {
                return ResourceManager.GetString("CancelJobConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解除锁定 的本地化字符串。
        /// </summary>
        public static string CancelLock {
            get {
                return ResourceManager.GetString("CancelLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要解除锁定吗？ 的本地化字符串。
        /// </summary>
        public static string CancelLockConfirm {
            get {
                return ResourceManager.GetString("CancelLockConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解除锁定不成功 的本地化字符串。
        /// </summary>
        public static string CancelLockNoSuccess {
            get {
                return ResourceManager.GetString("CancelLockNoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解除锁定成功 的本地化字符串。
        /// </summary>
        public static string CancelLockSuccess {
            get {
                return ResourceManager.GetString("CancelLockSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要取消选用此数据吗？ 的本地化字符串。
        /// </summary>
        public static string CancelMasterCodeConfirm {
            get {
                return ResourceManager.GetString("CancelMasterCodeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解除暂停 的本地化字符串。
        /// </summary>
        public static string CancelSuspend {
            get {
                return ResourceManager.GetString("CancelSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要解除暂停吗？ 的本地化字符串。
        /// </summary>
        public static string CancelSuspendConfirm {
            get {
                return ResourceManager.GetString("CancelSuspendConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解除暂停不成功 的本地化字符串。
        /// </summary>
        public static string CancelSuspendNoSuccess {
            get {
                return ResourceManager.GetString("CancelSuspendNoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解除暂停成功 的本地化字符串。
        /// </summary>
        public static string CancelSuspendSuccess {
            get {
                return ResourceManager.GetString("CancelSuspendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能删除主数据 的本地化字符串。
        /// </summary>
        public static string CanNotDeleteMainData {
            get {
                return ResourceManager.GetString("CanNotDeleteMainData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更换店铺 的本地化字符串。
        /// </summary>
        public static string ChangeShop {
            get {
                return ResourceManager.GetString("ChangeShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 District code not exists,Please check District code first. 的本地化字符串。
        /// </summary>
        public static string CheckDistrictCodeFirst {
            get {
                return ResourceManager.GetString("CheckDistrictCodeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请至少勾选一项状态 的本地化字符串。
        /// </summary>
        public static string CheckedStatus {
            get {
                return ResourceManager.GetString("CheckedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Estate/Road code not exists,Please check Estate/Road code first. 的本地化字符串。
        /// </summary>
        public static string CheckEstateRoadCodeFirst {
            get {
                return ResourceManager.GetString("CheckEstateRoadCodeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Type code not exists,Please check Model Type code first. 的本地化字符串。
        /// </summary>
        public static string CheckModelTypeCodeFirst {
            get {
                return ResourceManager.GetString("CheckModelTypeCodeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Type / Brand code not exists,Please check Model Type / Brand code first. 的本地化字符串。
        /// </summary>
        public static string CheckModelTypeOrBrandCodeFirst {
            get {
                return ResourceManager.GetString("CheckModelTypeOrBrandCodeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请单击修改按钮 的本地化字符串。
        /// </summary>
        public static string ClickModify {
            get {
                return ResourceManager.GetString("ClickModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to void it? 的本地化字符串。
        /// </summary>
        public static string CONFIRM_VOID {
            get {
                return ResourceManager.GetString("CONFIRM_VOID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定生效吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmActive {
            get {
                return ResourceManager.GetString("ConfirmActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认自动吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmAuto {
            get {
                return ResourceManager.GetString("ConfirmAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认关闭吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmClose {
            get {
                return ResourceManager.GetString("ConfirmClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定转换吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmConvert {
            get {
                return ResourceManager.GetString("ConfirmConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to confirm Job Adjustment? 的本地化字符串。
        /// </summary>
        public static string ConfirmedJobAdjust {
            get {
                return ResourceManager.GetString("ConfirmedJobAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认失效吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmInactive {
            get {
                return ResourceManager.GetString("ConfirmInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认手动吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmManual {
            get {
                return ResourceManager.GetString("ConfirmManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定保存吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmSave {
            get {
                return ResourceManager.GetString("ConfirmSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除吗？ 的本地化字符串。
        /// </summary>
        public static string ConfrimDel {
            get {
                return ResourceManager.GetString("ConfrimDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created By 的本地化字符串。
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creation Date 的本地化字符串。
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本店帐套座席组 的本地化字符串。
        /// </summary>
        public static string CURRENT_USER_GROUP {
            get {
                return ResourceManager.GetString("CURRENT_USER_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User :  的本地化字符串。
        /// </summary>
        public static string CurrentUser {
            get {
                return ResourceManager.GetString("CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Shop 的本地化字符串。
        /// </summary>
        public static string CurrShop {
            get {
                return ResourceManager.GetString("CurrShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截至日期必须大于等于起始日期 的本地化字符串。
        /// </summary>
        public static string DateCompareMsg {
            get {
                return ResourceManager.GetString("DateCompareMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束日期必须大于等于开始日期 的本地化字符串。
        /// </summary>
        public static string DateError {
            get {
                return ResourceManager.GetString("DateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询时间不合理,结束日期必须大于开始日期 的本地化字符串。
        /// </summary>
        public static string DateVaid {
            get {
                return ResourceManager.GetString("DateVaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日 的本地化字符串。
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Req 的本地化字符串。
        /// </summary>
        public static string DDL_CheckReq {
            get {
                return ResourceManager.GetString("DDL_CheckReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invoice 的本地化字符串。
        /// </summary>
        public static string DDL_InvoiceOnly {
            get {
                return ResourceManager.GetString("DDL_InvoiceOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Need 的本地化字符串。
        /// </summary>
        public static string DDL_Need {
            get {
                return ResourceManager.GetString("DDL_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Need 的本地化字符串。
        /// </summary>
        public static string DDL_NoNeed {
            get {
                return ResourceManager.GetString("DDL_NoNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product and Invoice 的本地化字符串。
        /// </summary>
        public static string DDL_ProductAndInvoice {
            get {
                return ResourceManager.GetString("DDL_ProductAndInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Valid 的本地化字符串。
        /// </summary>
        public static string DDL_Valid {
            get {
                return ResourceManager.GetString("DDL_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截至值必须大于等于起始值 的本地化字符串。
        /// </summary>
        public static string DecimalCompareMsg {
            get {
                return ResourceManager.GetString("DecimalCompareMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除吗？ 的本地化字符串。
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败 的本地化字符串。
        /// </summary>
        public static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        public static string DeleteSucceed {
            get {
                return ResourceManager.GetString("DeleteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定删除当前所勾选的记录 的本地化字符串。
        /// </summary>
        public static string DMSDeleteConfirm {
            get {
                return ResourceManager.GetString("DMSDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该记录状态禁止删除 的本地化字符串。
        /// </summary>
        public static string DMSProhibitDelStatus {
            get {
                return ResourceManager.GetString("DMSProhibitDelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该记录状态禁止编辑 的本地化字符串。
        /// </summary>
        public static string DMSProhibitEditStsD {
            get {
                return ResourceManager.GetString("DMSProhibitEditStsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string DropDownListDefaultItemText {
            get {
                return ResourceManager.GetString("DropDownListDefaultItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入确认新密码 的本地化字符串。
        /// </summary>
        public static string EnterConfirmPassword {
            get {
                return ResourceManager.GetString("EnterConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入数字 的本地化字符串。
        /// </summary>
        public static string EnterNumber {
            get {
                return ResourceManager.GetString("EnterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入新密码 的本地化字符串。
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询起始时间不得大于结束时间 的本地化字符串。
        /// </summary>
        public static string ErrBegDateMoreThanEndDate {
            get {
                return ResourceManager.GetString("ErrBegDateMoreThanEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询时间不能大于今天 的本地化字符串。
        /// </summary>
        public static string ErrMoreThanDateNow {
            get {
                return ResourceManager.GetString("ErrMoreThanDateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序错误 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前数据已经被其他数据所使用。 的本地化字符串。
        /// </summary>
        public static string ExistsSubData {
            get {
                return ResourceManager.GetString("ExistsSubData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冻结 的本地化字符串。
        /// </summary>
        public static string Frozen {
            get {
                return ResourceManager.GetString("Frozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要冻结吗？ 的本地化字符串。
        /// </summary>
        public static string FrozenConfirm {
            get {
                return ResourceManager.GetString("FrozenConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冻结状态不允许编辑 的本地化字符串。
        /// </summary>
        public static string FrozenEditError {
            get {
                return ResourceManager.GetString("FrozenEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冻结不成功 的本地化字符串。
        /// </summary>
        public static string FrozenNoSuccess {
            get {
                return ResourceManager.GetString("FrozenNoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冻结成功 的本地化字符串。
        /// </summary>
        public static string FrozenSuccess {
            get {
                return ResourceManager.GetString("FrozenSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全名 的本地化字符串。
        /// </summary>
        public static string FullNamex {
            get {
                return ResourceManager.GetString("FullNamex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name / Phone / Address inconsistencies. Can not operate Group Product.  的本地化字符串。
        /// </summary>
        public static string GroupValidateNotPass {
            get {
                return ResourceManager.GetString("GroupValidateNotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前已经为生效，不能改变为生效 的本地化字符串。
        /// </summary>
        public static string HasActive {
            get {
                return ResourceManager.GetString("HasActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前已经为自动，不能改变为自动 的本地化字符串。
        /// </summary>
        public static string HasAuto {
            get {
                return ResourceManager.GetString("HasAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经被冻结，不能再次冻结。 的本地化字符串。
        /// </summary>
        public static string HasFrozen {
            get {
                return ResourceManager.GetString("HasFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前已经为失效，不能改变为失效 的本地化字符串。
        /// </summary>
        public static string HasInactive {
            get {
                return ResourceManager.GetString("HasInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前已经为手动，不能改变为手动 的本地化字符串。
        /// </summary>
        public static string HasManual {
            get {
                return ResourceManager.GetString("HasManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您当前未被赋予检视权限，建议您向管理人员提出赋权申请。 的本地化字符串。
        /// </summary>
        public static string hasNoPermissionToOperate {
            get {
                return ResourceManager.GetString("hasNoPermissionToOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已被选用，不能重复操作。 的本地化字符串。
        /// </summary>
        public static string HasSelected {
            get {
                return ResourceManager.GetString("HasSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经被暂停，不能再次暂停。 的本地化字符串。
        /// </summary>
        public static string HasSuspend {
            get {
                return ResourceManager.GetString("HasSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经解锁登录，不能再次解锁 的本地化字符串。
        /// </summary>
        public static string HasUnlockLogin {
            get {
                return ResourceManager.GetString("HasUnlockLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经解锁工作台，不能再次解锁 的本地化字符串。
        /// </summary>
        public static string HasUnlockWP {
            get {
                return ResourceManager.GetString("HasUnlockWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正整数 的本地化字符串。
        /// </summary>
        public static string Input_plus_number {
            get {
                return ResourceManager.GetString("Input_plus_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Update Date 的本地化字符串。
        /// </summary>
        public static string LastUpdateDate {
            get {
                return ResourceManager.GetString("LastUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Updated By 的本地化字符串。
        /// </summary>
        public static string LastUpdatedBy {
            get {
                return ResourceManager.GetString("LastUpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多选 的本地化字符串。
        /// </summary>
        public static string LblMultipleChoice {
            get {
                return ResourceManager.GetString("LblMultipleChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单选 的本地化字符串。
        /// </summary>
        public static string LblRadio {
            get {
                return ResourceManager.GetString("LblRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string LOV_CANCEL {
            get {
                return ResourceManager.GetString("LOV_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勾选清空 的本地化字符串。
        /// </summary>
        public static string LOV_CLEAR {
            get {
                return ResourceManager.GetString("LOV_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勾选选取 的本地化字符串。
        /// </summary>
        public static string LOV_OK {
            get {
                return ResourceManager.GetString("LOV_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ＊ 的本地化字符串。
        /// </summary>
        public static string Mandatory {
            get {
                return ResourceManager.GetString("Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最多月份数必须大于最小月份数 的本地化字符串。
        /// </summary>
        public static string MaxMin {
            get {
                return ResourceManager.GetString("MaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大值输入错误,不能大于{0} 的本地化字符串。
        /// </summary>
        public static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string MessageInfoTitle {
            get {
                return ResourceManager.GetString("MessageInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        public static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小值输入错误,不能小于{0} 的本地化字符串。
        /// </summary>
        public static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改成功 的本地化字符串。
        /// </summary>
        public static string ModifySuccessed {
            get {
                return ResourceManager.GetString("ModifySuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改不成功 的本地化字符串。
        /// </summary>
        public static string ModifyUnsuccessed {
            get {
                return ResourceManager.GetString("ModifyUnsuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必填 的本地化字符串。
        /// </summary>
        public static string MustInput {
            get {
                return ResourceManager.GetString("MustInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前选择的操作必须选择记录。 的本地化字符串。
        /// </summary>
        public static string MustSelectRecord {
            get {
                return ResourceManager.GetString("MustSelectRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户必须至少拥有一个权限店铺 的本地化字符串。
        /// </summary>
        public static string MustSelectShop {
            get {
                return ResourceManager.GetString("MustSelectShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有被冻结，不能解除冻结。 的本地化字符串。
        /// </summary>
        public static string NoFrozen {
            get {
                return ResourceManager.GetString("NoFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有被锁定，不能解除锁定。 的本地化字符串。
        /// </summary>
        public static string NoLock {
            get {
                return ResourceManager.GetString("NoLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无此权限 的本地化字符串。
        /// </summary>
        public static string NoPermssion {
            get {
                return ResourceManager.GetString("NoPermssion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到任何记录！ 的本地化字符串。
        /// </summary>
        public static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模式本店未选用 的本地化字符串。
        /// </summary>
        public static string NoSelectMode {
            get {
                return ResourceManager.GetString("NoSelectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有被暂停，不能解除暂停。 的本地化字符串。
        /// </summary>
        public static string NoSuspend {
            get {
                return ResourceManager.GetString("NoSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是一个字母 的本地化字符串。
        /// </summary>
        public static string NotAlphabet {
            get {
                return ResourceManager.GetString("NotAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司用户不能解除冻结系统层面的角色 的本地化字符串。
        /// </summary>
        public static string NotCancelFrozenRoleByNS {
            get {
                return ResourceManager.GetString("NotCancelFrozenRoleByNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是一个字符 的本地化字符串。
        /// </summary>
        public static string NotChar {
            get {
                return ResourceManager.GetString("NotChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司用户不能编辑系统层面的角色 的本地化字符串。
        /// </summary>
        public static string NotEditRoleByNS {
            get {
                return ResourceManager.GetString("NotEditRoleByNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司用户不能冻结系统层面的角色 的本地化字符串。
        /// </summary>
        public static string NotFrozenRoleByNS {
            get {
                return ResourceManager.GetString("NotFrozenRoleByNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非整数 的本地化字符串。
        /// </summary>
        public static string NotInt {
            get {
                return ResourceManager.GetString("NotInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not the master parts,Can not modify Substitution information. 的本地化字符串。
        /// </summary>
        public static string NotMasterPartsPrompt {
            get {
                return ResourceManager.GetString("NotMasterPartsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是一个数字 的本地化字符串。
        /// </summary>
        public static string NotNumber {
            get {
                return ResourceManager.GetString("NotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未被选用，不能设置默认值。 的本地化字符串。
        /// </summary>
        public static string NotSelectToSetDefaultValue {
            get {
                return ResourceManager.GetString("NotSelectToSetDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据不合法 的本地化字符串。
        /// </summary>
        public static string NotValid {
            get {
                return ResourceManager.GetString("NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择客户没有车辆 的本地化字符串。
        /// </summary>
        public static string NoVehicle {
            get {
                return ResourceManager.GetString("NoVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string PagerBtnJumpText {
            get {
                return ResourceManager.GetString("PagerBtnJumpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页  的本地化字符串。
        /// </summary>
        public static string PagerFirst {
            get {
                return ResourceManager.GetString("PagerFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转到 的本地化字符串。
        /// </summary>
        public static string PagerGo {
            get {
                return ResourceManager.GetString("PagerGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转到第{0}页 的本地化字符串。
        /// </summary>
        public static string PagerJumpToFormat {
            get {
                return ResourceManager.GetString("PagerJumpToFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 末页 的本地化字符串。
        /// </summary>
        public static string PagerLast {
            get {
                return ResourceManager.GetString("PagerLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后一页 的本地化字符串。
        /// </summary>
        public static string PagerNext {
            get {
                return ResourceManager.GetString("PagerNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入1到{0}的数字 的本地化字符串。
        /// </summary>
        public static string PagerOverNumStr {
            get {
                return ResourceManager.GetString("PagerOverNumStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前一页 的本地化字符串。
        /// </summary>
        public static string PagerPrevious {
            get {
                return ResourceManager.GetString("PagerPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共有 {0} 条记录, 共 {1} 页, 每页 {2} 条记录,当前第 {3} 页 的本地化字符串。
        /// </summary>
        public static string PagerToolTip {
            get {
                return ResourceManager.GetString("PagerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数错误！ 的本地化字符串。
        /// </summary>
        public static string ParameterError {
            get {
                return ResourceManager.GetString("ParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非主零件，不能替换。 的本地化字符串。
        /// </summary>
        public static string PartsMasterPartsReplece {
            get {
                return ResourceManager.GetString("PartsMasterPartsReplece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码和确认新密码不一致 的本地化字符串。
        /// </summary>
        public static string PassNoEqualsConfirmPass {
            get {
                return ResourceManager.GetString("PassNoEqualsConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能使用此功能！注：属性必须为可使用的店选数据！ 的本地化字符串。
        /// </summary>
        public static string PropMustActiveAndShopSelect {
            get {
                return ResourceManager.GetString("PropMustActiveAndShopSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认日期重算吗？ 的本地化字符串。
        /// </summary>
        public static string RecalculateConfirm {
            get {
                return ResourceManager.GetString("RecalculateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录已经改变 的本地化字符串。
        /// </summary>
        public static string RecordChanged {
            get {
                return ResourceManager.GetString("RecordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录重复 的本地化字符串。
        /// </summary>
        public static string RecordDuplicate {
            get {
                return ResourceManager.GetString("RecordDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转到登录页 的本地化字符串。
        /// </summary>
        public static string RedirectToLogin {
            get {
                return ResourceManager.GetString("RedirectToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须输入该项 的本地化字符串。
        /// </summary>
        public static string RequiredMessage {
            get {
                return ResourceManager.GetString("RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须选择该项 的本地化字符串。
        /// </summary>
        public static string RequiredSelect {
            get {
                return ResourceManager.GetString("RequiredSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在相同的数据 的本地化字符串。
        /// </summary>
        public static string SameValue {
            get {
                return ResourceManager.GetString("SameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save And Confirm 的本地化字符串。
        /// </summary>
        public static string SaveAndConfirm {
            get {
                return ResourceManager.GetString("SaveAndConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请您先保存投诉单，再进行当前操作！ 的本地化字符串。
        /// </summary>
        public static string SaveComplaintFirst {
            get {
                return ResourceManager.GetString("SaveComplaintFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败 的本地化字符串。
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        public static string SaveSucceed {
            get {
                return ResourceManager.GetString("SaveSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please search data first. 的本地化字符串。
        /// </summary>
        public static string SearchFirst {
            get {
                return ResourceManager.GetString("SearchFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先搜索或搜索(客户档)后导出 的本地化字符串。
        /// </summary>
        public static string SearchFrist {
            get {
                return ResourceManager.GetString("SearchFrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否全部选用？ 的本地化字符串。
        /// </summary>
        public static string SelectAllConfirm {
            get {
                return ResourceManager.GetString("SelectAllConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pls. select Brand first. 的本地化字符串。
        /// </summary>
        public static string SelectBrandFrist {
            get {
                return ResourceManager.GetString("SelectBrandFrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pls. select District first. 的本地化字符串。
        /// </summary>
        public static string SelectDistrictFrist {
            get {
                return ResourceManager.GetString("SelectDistrictFrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pls. select Estate/Road first. 的本地化字符串。
        /// </summary>
        public static string SelectEstateRoadFrist {
            get {
                return ResourceManager.GetString("SelectEstateRoadFrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择导出字段 的本地化字符串。
        /// </summary>
        public static string SelectExportField {
            get {
                return ResourceManager.GetString("SelectExportField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要选用此数据吗？ 的本地化字符串。
        /// </summary>
        public static string SelectMasterCodeConfirm {
            get {
                return ResourceManager.GetString("SelectMasterCodeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择会员属性项目 的本地化字符串。
        /// </summary>
        public static string SelectMemberAttrItem {
            get {
                return ResourceManager.GetString("SelectMemberAttrItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pls. select Model Type first. 的本地化字符串。
        /// </summary>
        public static string SelectModelTypeFrist {
            get {
                return ResourceManager.GetString("SelectModelTypeFrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请您先勾选一条以上记录，再进行当前操作 的本地化字符串。
        /// </summary>
        public static string SelectMultiple {
            get {
                return ResourceManager.GetString("SelectMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string SelectNoItemText {
            get {
                return ResourceManager.GetString("SelectNoItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请您先勾选一条记录，再进行当前操作! 的本地化字符串。
        /// </summary>
        public static string SelectSingle {
            get {
                return ResourceManager.GetString("SelectSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must select a record from [Outstanding Order List] before you do this operation. 的本地化字符串。
        /// </summary>
        public static string SelectSingleFromOSList {
            get {
                return ResourceManager.GetString("SelectSingleFromOSList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string SelectYesItemText {
            get {
                return ResourceManager.GetString("SelectYesItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 店代码 的本地化字符串。
        /// </summary>
        public static string SHOP_CODE {
            get {
                return ResourceManager.GetString("SHOP_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当选择角色层面为店时，必须选择一个店! 的本地化字符串。
        /// </summary>
        public static string SHOP_MUST_SELECT {
            get {
                return ResourceManager.GetString("SHOP_MUST_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择店 的本地化字符串。
        /// </summary>
        public static string ShopLovTitle {
            get {
                return ResourceManager.GetString("ShopLovTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单选 的本地化字符串。
        /// </summary>
        public static string SingleSelected {
            get {
                return ResourceManager.GetString("SingleSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Sure {
            get {
                return ResourceManager.GetString("Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你还有数据没有保存，确定离开此页吗？ 的本地化字符串。
        /// </summary>
        public static string SureLeave {
            get {
                return ResourceManager.GetString("SureLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定进行此操作吗? 的本地化字符串。
        /// </summary>
        public static string SureLeave1 {
            get {
                return ResourceManager.GetString("SureLeave1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停 的本地化字符串。
        /// </summary>
        public static string Suspend {
            get {
                return ResourceManager.GetString("Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要暂停吗？ 的本地化字符串。
        /// </summary>
        public static string SuspendConfirm {
            get {
                return ResourceManager.GetString("SuspendConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停不成功 的本地化字符串。
        /// </summary>
        public static string SuspendNoSuccess {
            get {
                return ResourceManager.GetString("SuspendNoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停成功 的本地化字符串。
        /// </summary>
        public static string SuspendSuccess {
            get {
                return ResourceManager.GetString("SuspendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统代码 的本地化字符串。
        /// </summary>
        public static string SYS_CODE {
            get {
                return ResourceManager.GetString("SYS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间格式错误 的本地化字符串。
        /// </summary>
        public static string TimeTypeError {
            get {
                return ResourceManager.GetString("TimeTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到 的本地化字符串。
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特殊设定座席 的本地化字符串。
        /// </summary>
        public static string USER_CODE {
            get {
                return ResourceManager.GetString("USER_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特殊设定座席组 的本地化字符串。
        /// </summary>
        public static string USER_GROUP {
            get {
                return ResourceManager.GetString("USER_GROUP", resourceCulture);
            }
        }
    }
}
