//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSC.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Material {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Material() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSC.App_GlobalResources.Material", typeof(Material).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Allow Change 的本地化字符串。
        /// </summary>
        public static string AllowChange {
            get {
                return ResourceManager.GetString("AllowChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date From 的本地化字符串。
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date To 的本地化字符串。
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End date Must exclude the scope of the exist date time 的本地化字符串。
        /// </summary>
        public static string EndDateError {
            get {
                return ResourceManager.GetString("EndDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From date Must exclude the scope of the exist date time 的本地化字符串。
        /// </summary>
        public static string FromDateError {
            get {
                return ResourceManager.GetString("FromDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the scope of From Date and To Date has error 的本地化字符串。
        /// </summary>
        public static string FromToDateError {
            get {
                return ResourceManager.GetString("FromToDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Material Code 的本地化字符串。
        /// </summary>
        public static string MaterialCode {
            get {
                return ResourceManager.GetString("MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Material Description 的本地化字符串。
        /// </summary>
        public static string MaterialDesc {
            get {
                return ResourceManager.GetString("MaterialDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Material Price 的本地化字符串。
        /// </summary>
        public static string MaterialPrice {
            get {
                return ResourceManager.GetString("MaterialPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Material Price Date 的本地化字符串。
        /// </summary>
        public static string MaterialPriceDate {
            get {
                return ResourceManager.GetString("MaterialPriceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Material 的本地化字符串。
        /// </summary>
        public static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Material Unit Price 的本地化字符串。
        /// </summary>
        public static string MaterialUnitPrice {
            get {
                return ResourceManager.GetString("MaterialUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Type Code 的本地化字符串。
        /// </summary>
        public static string ModelTypeCode {
            get {
                return ResourceManager.GetString("ModelTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ToDate Must MoreThan FromDate 的本地化字符串。
        /// </summary>
        public static string ToDateMustMoreThanFromDate {
            get {
                return ResourceManager.GetString("ToDateMustMoreThanFromDate", resourceCulture);
            }
        }
    }
}
