//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSC.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSC.App_GlobalResources.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Reason Code - CSCP01010 的本地化字符串。
        /// </summary>
        public static string CSCP01010 {
            get {
                return ResourceManager.GetString("CSCP01010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Class - CSCP01020 的本地化字符串。
        /// </summary>
        public static string CSCP01020 {
            get {
                return ResourceManager.GetString("CSCP01020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currency - CSCP01030 的本地化字符串。
        /// </summary>
        public static string CSCP01030 {
            get {
                return ResourceManager.GetString("CSCP01030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exchange Rate - CSCP01040 的本地化字符串。
        /// </summary>
        public static string CSCP01040 {
            get {
                return ResourceManager.GetString("CSCP01040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supplier - CSCP01050 的本地化字符串。
        /// </summary>
        public static string CSCP01050 {
            get {
                return ResourceManager.GetString("CSCP01050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client - CSCP01060 的本地化字符串。
        /// </summary>
        public static string CSCP01060 {
            get {
                return ResourceManager.GetString("CSCP01060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shop Management - CSCS01010 的本地化字符串。
        /// </summary>
        public static string CSCS01010 {
            get {
                return ResourceManager.GetString("CSCS01010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Management - CSCS01020 的本地化字符串。
        /// </summary>
        public static string CSCS01020 {
            get {
                return ResourceManager.GetString("CSCS01020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role Management - CSCS01030 的本地化字符串。
        /// </summary>
        public static string CSCS01030 {
            get {
                return ResourceManager.GetString("CSCS01030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password History - CSCS01040 的本地化字符串。
        /// </summary>
        public static string CSCS01040 {
            get {
                return ResourceManager.GetString("CSCS01040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function Management - CSCS01050 的本地化字符串。
        /// </summary>
        public static string CSCS01050 {
            get {
                return ResourceManager.GetString("CSCS01050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brand - CSCS02010 的本地化字符串。
        /// </summary>
        public static string CSCS02010 {
            get {
                return ResourceManager.GetString("CSCS02010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service Group - CSCS02020 的本地化字符串。
        /// </summary>
        public static string CSCS02020 {
            get {
                return ResourceManager.GetString("CSCS02020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Master Code - CSCS02060 的本地化字符串。
        /// </summary>
        public static string CSCS02060 {
            get {
                return ResourceManager.GetString("CSCS02060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adress Code - CSCS02070 的本地化字符串。
        /// </summary>
        public static string CSCS02070 {
            get {
                return ResourceManager.GetString("CSCS02070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maintenance 的本地化字符串。
        /// </summary>
        public static string MNU_Setup {
            get {
                return ResourceManager.GetString("MNU_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        public static string MNU_System {
            get {
                return ResourceManager.GetString("MNU_System", resourceCulture);
            }
        }
    }
}
