//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSC.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProvinceCityAreaText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProvinceCityAreaText() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSC.App_GlobalResources.ProvinceCityAreaText", typeof(ProvinceCityAreaText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 区 的本地化字符串。
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区代码 的本地化字符串。
        /// </summary>
        public static string Area_Code {
            get {
                return ResourceManager.GetString("Area_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区全称 的本地化字符串。
        /// </summary>
        public static string Area_FullName {
            get {
                return ResourceManager.GetString("Area_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 市 的本地化字符串。
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 市代码 的本地化字符串。
        /// </summary>
        public static string City_Code {
            get {
                return ResourceManager.GetString("City_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 市全称 的本地化字符串。
        /// </summary>
        public static string City_FullName {
            get {
                return ResourceManager.GetString("City_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 省 的本地化字符串。
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 省代码 的本地化字符串。
        /// </summary>
        public static string Province_Code {
            get {
                return ResourceManager.GetString("Province_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 省全称 的本地化字符串。
        /// </summary>
        public static string Province_FullName {
            get {
                return ResourceManager.GetString("Province_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区 - 新增 的本地化字符串。
        /// </summary>
        public static string Title_Area_Add {
            get {
                return ResourceManager.GetString("Title_Area_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区 - 编辑 的本地化字符串。
        /// </summary>
        public static string Title_Area_Edit {
            get {
                return ResourceManager.GetString("Title_Area_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 市 - 新增 的本地化字符串。
        /// </summary>
        public static string Title_City_Add {
            get {
                return ResourceManager.GetString("Title_City_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 市 - 编辑 的本地化字符串。
        /// </summary>
        public static string Title_City_Edit {
            get {
                return ResourceManager.GetString("Title_City_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 省 - 新增 的本地化字符串。
        /// </summary>
        public static string Title_Province_Add {
            get {
                return ResourceManager.GetString("Title_Province_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 省 - 编辑 的本地化字符串。
        /// </summary>
        public static string Title_Province_Edit {
            get {
                return ResourceManager.GetString("Title_Province_Edit", resourceCulture);
            }
        }
    }
}
