//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSC.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShopText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShopText() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSC.App_GlobalResources.ShopText", typeof(ShopText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 地址(第1行) 的本地化字符串。
        /// </summary>
        public static string AddrLine1 {
            get {
                return ResourceManager.GetString("AddrLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址(第2行) 的本地化字符串。
        /// </summary>
        public static string AddrLine2 {
            get {
                return ResourceManager.GetString("AddrLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区 的本地化字符串。
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Default Godown 的本地化字符串。
        /// </summary>
        public static string BtnSetDefult {
            get {
                return ResourceManager.GetString("BtnSetDefult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Business Unit Code 的本地化字符串。
        /// </summary>
        public static string BUCode {
            get {
                return ResourceManager.GetString("BUCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 市 的本地化字符串。
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 店代码 的本地化字符串。
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Godown 的本地化字符串。
        /// </summary>
        public static string DefultGodownSHOW {
            get {
                return ResourceManager.GetString("DefultGodownSHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮件账号 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传真号码 的本地化字符串。
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 店全名 的本地化字符串。
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 店名称 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Password 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话地区号码 的本地化字符串。
        /// </summary>
        public static string PhoneAreaCode {
            get {
                return ResourceManager.GetString("PhoneAreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话号码1 的本地化字符串。
        /// </summary>
        public static string PhoneNo1 {
            get {
                return ResourceManager.GetString("PhoneNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话号码2 的本地化字符串。
        /// </summary>
        public static string PhoneNo2 {
            get {
                return ResourceManager.GetString("PhoneNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮政编码 的本地化字符串。
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 省 的本地化字符串。
        /// </summary>
        public static string Prov {
            get {
                return ResourceManager.GetString("Prov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Province/SAR 的本地化字符串。
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Godown 的本地化字符串。
        /// </summary>
        public static string SetDefultGodown {
            get {
                return ResourceManager.GetString("SetDefultGodown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 店资料 的本地化字符串。
        /// </summary>
        public static string ShopEdit {
            get {
                return ResourceManager.GetString("ShopEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 店列表 的本地化字符串。
        /// </summary>
        public static string ShopList {
            get {
                return ResourceManager.GetString("ShopList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shop Type 的本地化字符串。
        /// </summary>
        public static string ShopType {
            get {
                return ResourceManager.GetString("ShopType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网站地址 的本地化字符串。
        /// </summary>
        public static string WebUrl {
            get {
                return ResourceManager.GetString("WebUrl", resourceCulture);
            }
        }
    }
}
