//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteMapLocalizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteMapLocalizations() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SiteMapLocalizations", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Address Code 的本地化字符串。
        /// </summary>
        internal static string AddressCodeTitle {
            get {
                return ResourceManager.GetString("AddressCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adjust Job 的本地化字符串。
        /// </summary>
        internal static string AdjustJobTitle {
            get {
                return ResourceManager.GetString("AdjustJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录查询 的本地化字符串。
        /// </summary>
        internal static string AuditLogTitle {
            get {
                return ResourceManager.GetString("AuditLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brand Code 的本地化字符串。
        /// </summary>
        internal static string BrandCodeTitle {
            get {
                return ResourceManager.GetString("BrandCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码变更 的本地化字符串。
        /// </summary>
        internal static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Charge Code 的本地化字符串。
        /// </summary>
        internal static string ChargeCodeTitle {
            get {
                return ResourceManager.GetString("ChargeCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client Maintenance 的本地化字符串。
        /// </summary>
        internal static string ClientTitle {
            get {
                return ResourceManager.GetString("ClientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Master Code 的本地化字符串。
        /// </summary>
        internal static string CodeTypeTitle {
            get {
                return ResourceManager.GetString("CodeTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contractor 的本地化字符串。
        /// </summary>
        internal static string Contractor {
            get {
                return ResourceManager.GetString("Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currency 的本地化字符串。
        /// </summary>
        internal static string CurrencyTitle {
            get {
                return ResourceManager.GetString("CurrencyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Invoice 的本地化字符串。
        /// </summary>
        internal static string CustomerInvoiceTitle {
            get {
                return ResourceManager.GetString("CustomerInvoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exchange Rate 的本地化字符串。
        /// </summary>
        internal static string ExchangeRateTitle {
            get {
                return ResourceManager.GetString("ExchangeRateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能管理 的本地化字符串。
        /// </summary>
        internal static string FunctionTitle {
            get {
                return ResourceManager.GetString("FunctionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        internal static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID/OD Order 的本地化字符串。
        /// </summary>
        internal static string IDODOrderTitle {
            get {
                return ResourceManager.GetString("IDODOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job Important Field Approval 的本地化字符串。
        /// </summary>
        internal static string JobImportantFieldApprovalTitle {
            get {
                return ResourceManager.GetString("JobImportantFieldApprovalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter Job Result and Complete 的本地化字符串。
        /// </summary>
        internal static string JobResultTitle {
            get {
                return ResourceManager.GetString("JobResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maintenance PriceAudit Report 的本地化字符串。
        /// </summary>
        internal static string MaintenancePriceAuditReportTitle {
            get {
                return ResourceManager.GetString("MaintenancePriceAuditReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Material 的本地化字符串。
        /// </summary>
        internal static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Code 的本地化字符串。
        /// </summary>
        internal static string ModelTitle {
            get {
                return ResourceManager.GetString("ModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Type 的本地化字符串。
        /// </summary>
        internal static string ModelTypeTitle {
            get {
                return ResourceManager.GetString("ModelTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Take Order 的本地化字符串。
        /// </summary>
        internal static string OrderTakeTitle {
            get {
                return ResourceManager.GetString("OrderTakeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outstanding Job Enquiry 的本地化字符串。
        /// </summary>
        internal static string OutstandingJobEnquiryTitle {
            get {
                return ResourceManager.GetString("OutstandingJobEnquiryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数管理 的本地化字符串。
        /// </summary>
        internal static string ParameterTitle {
            get {
                return ResourceManager.GetString("ParameterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PartsClass 的本地化字符串。
        /// </summary>
        internal static string PartsClass {
            get {
                return ResourceManager.GetString("PartsClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parts Maintenance 的本地化字符串。
        /// </summary>
        internal static string PartsMaintenanceTitle {
            get {
                return ResourceManager.GetString("PartsMaintenanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Class 的本地化字符串。
        /// </summary>
        internal static string ProductClassTitle {
            get {
                return ResourceManager.GetString("ProductClassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Information 的本地化字符串。
        /// </summary>
        internal static string ProductInformationTitle {
            get {
                return ResourceManager.GetString("ProductInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 省/市/区管理 的本地化字符串。
        /// </summary>
        internal static string ProvinceCityAreaTitle {
            get {
                return ResourceManager.GetString("ProvinceCityAreaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quotation 的本地化字符串。
        /// </summary>
        internal static string QuotationTitle {
            get {
                return ResourceManager.GetString("QuotationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reason Code 的本地化字符串。
        /// </summary>
        internal static string ReasonCodeTitle {
            get {
                return ResourceManager.GetString("ReasonCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refund Maintenance Agreement 的本地化字符串。
        /// </summary>
        internal static string RefundMaintAgreementTitle {
            get {
                return ResourceManager.GetString("RefundMaintAgreementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reorder Factor 的本地化字符串。
        /// </summary>
        internal static string ReorderFactorTitle {
            get {
                return ResourceManager.GetString("ReorderFactorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repair Code 的本地化字符串。
        /// </summary>
        internal static string RepairCodeTitle {
            get {
                return ResourceManager.GetString("RepairCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result Code 的本地化字符串。
        /// </summary>
        internal static string ResultCodeTitle {
            get {
                return ResourceManager.GetString("ResultCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色管理 的本地化字符串。
        /// </summary>
        internal static string RoleTitle {
            get {
                return ResourceManager.GetString("RoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service Group 的本地化字符串。
        /// </summary>
        internal static string ServiceGroupTitle {
            get {
                return ResourceManager.GetString("ServiceGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 店管理 的本地化字符串。
        /// </summary>
        internal static string ShopTitle {
            get {
                return ResourceManager.GetString("ShopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supplier Maintenance 的本地化字符串。
        /// </summary>
        internal static string SupplierTitle {
            get {
                return ResourceManager.GetString("SupplierTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Technician 的本地化字符串。
        /// </summary>
        internal static string Technician {
            get {
                return ResourceManager.GetString("Technician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        internal static string UserTitle {
            get {
                return ResourceManager.GetString("UserTitle", resourceCulture);
            }
        }
    }
}
