//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSC.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserText() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSC.App_GlobalResources.UserText", typeof(UserText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 有效 的本地化字符串。
        /// </summary>
        public static string ActiveFlag {
            get {
                return ResourceManager.GetString("ActiveFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理 的本地化字符串。
        /// </summary>
        public static string AdminFlag {
            get {
                return ResourceManager.GetString("AdminFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你还有数据没有保存，确定改变店吗？ 的本地化字符串。
        /// </summary>
        public static string ChangeShopMsg {
            get {
                return ResourceManager.GetString("ChangeShopMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建日期 的本地化字符串。
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public static string EditTab {
            get {
                return ResourceManager.GetString("EditTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由 的本地化字符串。
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定日期 的本地化字符串。
        /// </summary>
        public static string FrozenDate {
            get {
                return ResourceManager.GetString("FrozenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定 的本地化字符串。
        /// </summary>
        public static string FrozenFlag {
            get {
                return ResourceManager.GetString("FrozenFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能 的本地化字符串。
        /// </summary>
        public static string FunctionCode {
            get {
                return ResourceManager.GetString("FunctionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明 的本地化字符串。
        /// </summary>
        public static string FunctionDesc {
            get {
                return ResourceManager.GetString("FunctionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string FunctionType {
            get {
                return ResourceManager.GetString("FunctionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BUTTON 的本地化字符串。
        /// </summary>
        public static string FunctionTypeBTN {
            get {
                return ResourceManager.GetString("FunctionTypeBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FORM 的本地化字符串。
        /// </summary>
        public static string FunctionTypeFORM {
            get {
                return ResourceManager.GetString("FunctionTypeFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PASSWORD 的本地化字符串。
        /// </summary>
        public static string FunctionTypePWD {
            get {
                return ResourceManager.GetString("FunctionTypePWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 REPORT 的本地化字符串。
        /// </summary>
        public static string FunctionTypeRPT {
            get {
                return ResourceManager.GetString("FunctionTypeRPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BUTTON 的本地化字符串。
        /// </summary>
        public static string FuncTypeBTN {
            get {
                return ResourceManager.GetString("FuncTypeBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FORM 的本地化字符串。
        /// </summary>
        public static string FuncTypeFORM {
            get {
                return ResourceManager.GetString("FuncTypeFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PASSWORD 的本地化字符串。
        /// </summary>
        public static string FuncTypePWD {
            get {
                return ResourceManager.GetString("FuncTypePWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 REPORT 的本地化字符串。
        /// </summary>
        public static string FuncTypeRPT {
            get {
                return ResourceManager.GetString("FuncTypeRPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        public static string InsertFlag {
            get {
                return ResourceManager.GetString("InsertFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表 的本地化字符串。
        /// </summary>
        public static string ListTab {
            get {
                return ResourceManager.GetString("ListTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        public static string RoleCode {
            get {
                return ResourceManager.GetString("RoleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明 的本地化字符串。
        /// </summary>
        public static string RoleDSC {
            get {
                return ResourceManager.GetString("RoleDSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简述 的本地化字符串。
        /// </summary>
        public static string RoleSDSC {
            get {
                return ResourceManager.GetString("RoleSDSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 层面 的本地化字符串。
        /// </summary>
        public static string RoleType {
            get {
                return ResourceManager.GetString("RoleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 店 的本地化字符串。
        /// </summary>
        public static string RoleTypeSH {
            get {
                return ResourceManager.GetString("RoleTypeSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统 的本地化字符串。
        /// </summary>
        public static string RoleTypeSY {
            get {
                return ResourceManager.GetString("RoleTypeSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存用户角色成功 的本地化字符串。
        /// </summary>
        public static string SaveRoleSucceed {
            get {
                return ResourceManager.GetString("SaveRoleSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存用户角色不成功 的本地化字符串。
        /// </summary>
        public static string SaveRoleUnSucceed {
            get {
                return ResourceManager.GetString("SaveRoleUnSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 店 的本地化字符串。
        /// </summary>
        public static string ShopCode {
            get {
                return ResourceManager.GetString("ShopCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 店总数 的本地化字符串。
        /// </summary>
        public static string ShopCount {
            get {
                return ResourceManager.GetString("ShopCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停日期 的本地化字符串。
        /// </summary>
        public static string SuspendDate {
            get {
                return ResourceManager.GetString("SuspendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停 的本地化字符串。
        /// </summary>
        public static string SuspendFlag {
            get {
                return ResourceManager.GetString("SuspendFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统角色 的本地化字符串。
        /// </summary>
        public static string SystemRole {
            get {
                return ResourceManager.GetString("SystemRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用系统 的本地化字符串。
        /// </summary>
        public static string SystemScope {
            get {
                return ResourceManager.GetString("SystemScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 至 的本地化字符串。
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string UpdateFlag {
            get {
                return ResourceManager.GetString("UpdateFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当用户在某个店中被使用时,不允许剔除店的勾选。 的本地化字符串。
        /// </summary>
        public static string USER_USING {
            get {
                return ResourceManager.GetString("USER_USING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户号 的本地化字符串。
        /// </summary>
        public static string UserCode {
            get {
                return ResourceManager.GetString("UserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名称 的本地化字符串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户角色 的本地化字符串。
        /// </summary>
        public static string UserRoleTab {
            get {
                return ResourceManager.GetString("UserRoleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户类型 的本地化字符串。
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司用户 的本地化字符串。
        /// </summary>
        public static string UserTypeNS {
            get {
                return ResourceManager.GetString("UserTypeNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统用户 的本地化字符串。
        /// </summary>
        public static string UserTypeSA {
            get {
                return ResourceManager.GetString("UserTypeSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检视功能 的本地化字符串。
        /// </summary>
        public static string ViewRoleFunc {
            get {
                return ResourceManager.GetString("ViewRoleFunc", resourceCulture);
            }
        }
    }
}
