//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Framework.Security.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exception {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exception() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Framework.Security.Resources.Exception", typeof(Exception).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 密码输入错误次数已达到上限 的本地化字符串。
        /// </summary>
        internal static string HasExceededTheMaxInvalidPasswordAttempts {
            get {
                return ResourceManager.GetString("HasExceededTheMaxInvalidPasswordAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alpha characters can not be less than {0} bit 的本地化字符串。
        /// </summary>
        internal static string MinAlphaChar {
            get {
                return ResourceManager.GetString("MinAlphaChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Non-alpha characters can not be less than {0} bit 的本地化字符串。
        /// </summary>
        internal static string MinNonAlphaChar {
            get {
                return ResourceManager.GetString("MinNonAlphaChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Numeric characters can not be less than {0} bit 的本地化字符串。
        /// </summary>
        internal static string MinNumChar {
            get {
                return ResourceManager.GetString("MinNumChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码已超过有效期 的本地化字符串。
        /// </summary>
        internal static string PasswordIsEffected {
            get {
                return ResourceManager.GetString("PasswordIsEffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码错误 的本地化字符串。
        /// </summary>
        internal static string PasswordIsError {
            get {
                return ResourceManager.GetString("PasswordIsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空 的本地化字符串。
        /// </summary>
        internal static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能小于{0}位 的本地化字符串。
        /// </summary>
        internal static string PasswordRequiredMinLengthFormat {
            get {
                return ResourceManager.GetString("PasswordRequiredMinLengthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last {0} passwords can&apos;t use. 的本地化字符串。
        /// </summary>
        internal static string PasswordReusePrevention {
            get {
                return ResourceManager.GetString("PasswordReusePrevention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不能为空 的本地化字符串。
        /// </summary>
        internal static string UserNameIsRequired {
            get {
                return ResourceManager.GetString("UserNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在 的本地化字符串。
        /// </summary>
        internal static string UserNotExists {
            get {
                return ResourceManager.GetString("UserNotExists", resourceCulture);
            }
        }
    }
}
