/**********************************************************************/
-- Description:	 Get Exchange Rate
---------------------------------------------------------------------
-- Action		Date			Staff		Version		Remarks
-- Create	 	2013-06-21		LM		1.00.00
---------------------------------------------------------------------
/**********************************************************************/
	Create Function fnGetExchangeRate(
		@CCY_ID BIGINT = 0,
		@DATE DATETIME,
		@EXCHANGE_RATE_TYPE nvarchar(10) =N'',
		@BU_CODE		nvarchar(10) = N''
	)
	RETURNS decimal(14,8)
	AS
	BEGIN
		declare @MAXDATE datetime,@rate decimal(14,8)
		set @rate = null

		--select @MAXDATE = MAX(EXCH_RATE_DATE) FROM EXCHANGE_RATE WHERE CCY_ID = @CCY_ID and EXCH_RATE_DATE <=@DATE AND BU_CODE =@BU_CODE
		--IF(@MAXDATE IS NULL OR @MAXDATE = N'')
		--BEGIN		
		--	RETURN @rate;
		--END

		--SELECT @rate = EXCHANGE_RATE.EXCH_RATE
		--FROM CURRENCY INNER JOIN EXCHANGE_RATE ON CURRENCY.CCY_ID = EXCHANGE_RATE.CCY_ID
		--WHERE CURRENCY.CCY_ID = @CCY_ID AND EXCHANGE_RATE.EXCH_RATE_DATE = @MAXDATE AND CURRENCY.BU_CODE = @BU_CODE

		if(exists(select 1 from CURRENCY where CURRENCY.CCY_ID = @CCY_ID AND CURRENCY.BASE_CCY_IND = N'Y' AND CURRENCY.BU_CODE = @BU_CODE))
		BEGIN
			SET @rate = 1 --基准货币
			RETURN @RATE;
		END

		SELECT TOP 1 @rate = EXCHANGE_RATE.EXCH_RATE
		FROM CURRENCY INNER JOIN EXCHANGE_RATE ON CURRENCY.CCY_ID = EXCHANGE_RATE.CCY_ID
		WHERE  CURRENCY.CCY_ID = @CCY_ID AND EXCHANGE_RATE_TYPE = @EXCHANGE_RATE_TYPE AND CONVERT(NVARCHAR(10),EXCHANGE_RATE.EXCH_RATE_DATE,23)<=CONVERT(NVARCHAR(10),@DATE,23) AND CURRENCY.BU_CODE = @BU_CODE
		ORDER BY EXCHANGE_RATE.EXCH_RATE_DATE DESC
		return @rate;
	END
GO

--PARTS_FACTORY_PRICE 按parts_id 来取

Create Function fnGetExchangeRateByPartsID(
	@DATE DATETIME,
	@PARTS_ID BIGINT = 0,
	@EXCHANGE_RATE_TYPE nvarchar(10) =N'',
	@BU_CODE		nvarchar(10) = N''
)
RETURNS decimal(14,8)
AS
BEGIN
	declare @MAXDATE datetime,@rate decimal(14,8)
	set @rate = null
	DECLARE @CCY_ID BIGINT,@BASE_CCY_IND NVARCHAR(1)
	
	--SELECT TOP 1 @CCY_ID = CCY_ID FROM PARTS_FACTORY_PRICE  where PARTS_ID = @PARTS_ID AND EFFECTIVE_DATE<=@DATE and BU_CODE = @BU_CODE ORDER BY EFFECTIVE_DATE DESC

	--另一种写法
	--WITH CTE AS(
	--SELECT TOP 1 CCY_ID FROM PARTS_FACTORY_PRICE  where PARTS_ID = @PARTS_ID AND EFFECTIVE_DATE<=@DATE and BU_CODE = @BU_CODE ORDER BY EFFECTIVE_DATE DESC
	--)
	--SELECT TOP 1 @rate = EXCHANGE_RATE.EXCH_RATE
	--FROM CURRENCY INNER JOIN EXCHANGE_RATE ON CURRENCY.CCY_ID = EXCHANGE_RATE.CCY_ID
	--	 INNER JOIN CTE ON CTE.CCY_ID = CURRENCY.CCY_ID
	--WHERE  EXCHANGE_RATE.EXCH_RATE_DATE <= @DATE AND CURRENCY.BU_CODE = @BU_CODE
	--ORDER BY EXCHANGE_RATE.EXCH_RATE_DATE DESC


	SELECT TOP 1 @BASE_CCY_IND = CURRENCY.BASE_CCY_IND
	FROM CURRENCY INNER JOIN PARTS_FACTORY_PRICE ON PARTS_FACTORY_PRICE.CCY_ID = CURRENCY.CCY_ID AND PARTS_FACTORY_PRICE.PARTS_ID = @PARTS_ID
	WHERE PARTS_FACTORY_PRICE.EFFECTIVE_DATE<=@DATE
	ORDER BY PARTS_FACTORY_PRICE.EFFECTIVE_DATE DESC

	IF(@BASE_CCY_IND = N'Y')
	BEGIN
		SET @rate = 1
		RETURN @rate
	END

	SELECT TOP 1 @rate = EXCHANGE_RATE.EXCH_RATE ,@BASE_CCY_IND = CURRENCY.BASE_CCY_IND
	FROM CURRENCY INNER JOIN EXCHANGE_RATE ON CURRENCY.CCY_ID = EXCHANGE_RATE.CCY_ID
		 INNER JOIN PARTS_FACTORY_PRICE ON PARTS_FACTORY_PRICE.CCY_ID = CURRENCY.CCY_ID AND PARTS_FACTORY_PRICE.PARTS_ID = @PARTS_ID
	WHERE  
	CONVERT(NVARCHAR(10),EXCHANGE_RATE.EXCH_RATE_DATE,23)<=CONVERT(NVARCHAR(10),@DATE,23) AND CURRENCY.BU_CODE = @BU_CODE AND PARTS_FACTORY_PRICE.EFFECTIVE_DATE<=@DATE AND EXCHANGE_RATE_TYPE = @EXCHANGE_RATE_TYPE
	ORDER BY EFFECTIVE_DATE DESC,EXCHANGE_RATE.EXCH_RATE_DATE DESC

	return @rate;
END