CREATE TABLE SY_TRANSACTION_DATE
(
	TRANS_DATE_ID			bigint			NOT NULL	IDENTITY(1,1)
	,BU_CODE				nvarchar(10)	NOT NULL
	,TRAN_DATE				datetime		NOT NULL 
	,CREATED_BY				bigint			NOT NULL
	,CREATION_DATE			datetime		NOT NULL
	,LAST_UPDATED_BY		bigint			NOT NULL
	,LAST_UPDATE_DATE		datetime		NOT NULL
	,CONSTRAINT PK_SY_TRANSACTION_DATE PRIMARY KEY (TRANS_DATE_ID) ON [PRIMARY]
	,CONSTRAINT FK_SY_TRANSACTION_DATE_BU FOREIGN KEY(BU_CODE) REFERENCES BUSINESS_UNIT (BU_CODE)
) ON [PRIMARY]
GO
