DECLARE @SYS_CODE		nvarchar(4)		= N'CSC';
DECLARE @CUR_USER_ID	bigint			= 0;
DECLARE @CUR_DATE		datetime		= GETDATE();

INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 6	, N'CSCS02010'	, N'BRAND-CSCS02010'						, N'CSCS02010', N'N', N'CS',			@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 7	, N'CSCS02020'	, N'SERVICE_GROUP-CSCS02020'				, N'CSCS02020', N'N', N'CS',			@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 8	, N'CSCP01010'	, N'Reason Code-CSCP01010'					, N'CSCP01010', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 9	, N'CSCP01020'	, N'Product Class-CSCP01020'				, N'CSCP01020', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 10	, N'CSCP01030'	, N'Currency-CSCP01030'						, N'CSCP01030', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 11	, N'CSCP01040'	, N'Exchange Rate-CSCP01040'				, N'CSCP01040', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 12	, N'CSCS02030'	, N'Result Code-CSCS02030'					, N'CSCS02030', N'N', N'CS',			@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 13	, N'CSCS02040'	, N'Repair Code-CSCS02040'					, N'CSCS02040', N'N', N'CS',			@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 14	, N'CSCS02050'	, N'Charge Code-CSCS02050'					, N'CSCS02050', N'N', N'CS',			@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 15	, N'CSCS02060'	, N'Code Type-CSCS02060'					, N'CSCS02060', N'N', N'CS',			@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 16	, N'CSCS02070'	, N'Adress Code-CSCS02070'					, N'CSCS02070', N'N', N'CS',			@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE; 


INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 17	, N'CSCP01050'	, N'Supplier-CSCP01050'						, N'CSCP01050', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 18	, N'CSCP01060'	, N'Customer-CSCP01060'						, N'CSCP01060', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 19	, N'CSCS02080'	, N'Model Class-CSCS02080'					, N'CSCS02080', N'N', N'CS',			@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 20	, N'CSCS02090'	, N'Material-CSCS02090'						, N'CSCS02090', N'N', N'CS',			@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 21	, N'CSCS03010'	, N'Model Type-CSCS03010'					, N'CSCS03010', N'N', N'CS',			@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;

--add on 2013-04-18
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 22	, N'CSCS03020'	, N'Model Code-CSCS03020'					, N'CSCS03020', N'N', N'CS',			@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 23	, N'CSCS03030'	, N'Symptom-CSCS03030'						, N'CSCS03030', N'N', N'CS',			@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 24	, N'CSCP01070'	, N'Parts Class-CSCP01070'					, N'CSCP01070', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 25	, N'CSCP01080'	, N'Reorder Factor-CSCP01080'				, N'CSCP01080', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;

--add on 2013-04-23
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 26	, N'CSCP02010'	, N'Parts Maintenance-CSCP02010'			, N'CSCP02010', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;

--add on 2013-04-24
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 27	, N'CSCP01090'	, N'Category Code Maintenance-CSCP01090'	, N'CSCP01090', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;

--add on 2013-04-25
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 28	, N'CSCP02020'	, N'Bin Location-CSCP02020'					, N'CSCP02020', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;

--add on 2013-04-27
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 29	, N'CSCP02030'	, N'Godown Code-CSCP02030'					, N'CSCP02030', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-05-03
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 30	, N'CSCS03040'	, N'Maintenance Policy-CSCS03040'			, N'CSCS03040', N'N', N'CS',			@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-05-07
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 31	, N'CSCS03050'	, N'Product Information-CSCS03050'			, N'CSCS03050', N'N', N'CS',			@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 32	, N'CSCS03060'	, N'Technician Code-CSCS03060'				, N'CSCS03060', N'N', N'CS',			@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 33	, N'CSCS03070'	, N'Contractor-CSCS03070'					, N'CSCS03070', N'N', N'CS',			@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 34	, N'CSCS03080'	, N'Job Assign Rule-CSCS03080'				, N'CSCS03080', N'N', N'CS',			@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-05-15
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 35	, N'CSCP02040'	, N'Parts Factory Price Maintenance-CSCP02040'		, N'CSCP02040', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 36	, N'CSCP02050'	, N'Parts Selling Price Maintenance-CSCP02050'		, N'CSCP02050', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 37	, N'CSCP02060'	, N'Purchase Order Maintenance-CSCP02060'			, N'CSCP02060', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 38	, N'CSCS03090'	, N'Job Labour Fee-CSCS03090'						, N'CSCS03090', N'N', N'CS',			@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-05-15 for report
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 501	, N'CSCPR01010'	, N'Purchase Order Report-CSCPR01010'										, N'CSCPR01010', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 502	, N'CSCPR01020'	, N'Purchase Receiving Correction Report-CSCPR01020'						, N'CSCPR01020', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 503	, N'CSCPR01030'	, N'Purchase Order Suggest List-CSCPR01030'									, N'CSCPR01030', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 504	, N'CSCPR01040'	, N'Purchase Analysis Report-CSCPR01040'									, N'CSCPR01040', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 505	, N'CSCPR01050'	, N'Counter Sales Report-CSCPR01050'										, N'CSCPR01050', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 506	, N'CSCPR01060'	, N'Counter Sales Return Report-CSCPR01060'									, N'CSCPR01060', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 507	, N'CSCPR01070'	, N'Outstanding Parts By Technician-CSCPR01070'								, N'CSCPR01070', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 508	, N'CSCPR01080'	, N'Outstanding Parts History By Technician-CSCPR01080'						, N'CSCPR01080', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 509	, N'CSCPR01090'	, N'Technician Parts Movement Report-CSCPR01090'							, N'CSCPR01090', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 510	, N'CSCPR02010'	, N'Stock Movement Report-CSCPR02010'										, N'CSCPR02010', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 511	, N'CSCPR02020'	, N'Stock Adjustment Transaction Report-CSCPR02020'							, N'CSCPR02020', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 512	, N'CSCPR02030'	, N'Stock Value Report-CSCPR02030'											, N'CSCPR02030', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 513	, N'CSCPR02040'	, N'Stock Aging By Brand By Type-CSCPR02040'								, N'CSCPR02040', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 514	, N'CSCPR02050'	, N'Stock Aging By Brand-CSCPR02050'										, N'CSCPR02050', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 515	, N'CSCPR02060'	, N'Stock Aging By Brand By Parts-CSCPR02060'								, N'CSCPR02060', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 516	, N'CSCPR02070'	, N'Stock Take Report-CSCPR02070'											, N'CSCPR02070', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 517	, N'CSCPR02080'	, N'Stock Take Discrepancy Report-CSCPR02080'								, N'CSCPR02080', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 518	, N'CSCPR02090'	, N'Wait Order Stock Arrival Alert List-CSCPR02090'							, N'CSCPR02090', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 519	, N'CSCPR03010'	, N'Parts Sales Analysis Report-CSCPR03010'									, N'CSCPR03010', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 520	, N'CSCPR03020'	, N'Stock Transfer Note-CSCPR03020'											, N'CSCPR03020', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 521	, N'CSCPR03030'	, N'AP Invoice Report-CSCPR03030'											, N'CSCPR03030', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 522	, N'CSCPR03040'	, N'Material Account Distribution Detail-CSCPR03040'						, N'CSCPR03040', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 523	, N'CSCPR03050'	, N'Material Account Distribution Summary-CSCPR03050'						, N'CSCPR03050', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 524	, N'CSCPR03060'	, N'Daily Cost Consumption Summary Report-CSCPR03060'						, N'CSCPR03060', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 525	, N'CSCPR03070'	, N'Daily Job Pick Slip Report-CSCPR03070'									, N'CSCPR03070', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 526	, N'CSCPR03080'	, N'Daily Job Report-CSCPR03080'											, N'CSCPR03080', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 527	, N'CSCPR03090'	, N'Technician Daily Job List-CSCPR03090'									, N'CSCPR03090', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 528	, N'CSCPR04010'	, N'Outstanding Job Alert Report By Technician-CSCPR04010'					, N'CSCPR04010', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 529	, N'CSCPR04020'	, N'ID / OD Check List-CSCPR04020'											, N'CSCPR04020', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 530	, N'CSCPR04030'	, N'Daily Received Transaction Report-CSCPR04030'							, N'CSCPR04030', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 531	, N'CSCPR04040'	, N'Debtor Invoice Report-CSCPR04040'										, N'CSCPR04040', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 532	, N'CSCPR04050'	, N'AR Settlement History Report-CSCPR04050'								, N'CSCPR04050', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 533	, N'CSCPR04060'	, N'Debtor Aging Report-CSCPR04060'											, N'CSCPR04060', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 534	, N'CSCPR04070'	, N'Sales Analysis By Maint Type-CSCPR04070'								, N'CSCPR04070', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 535	, N'CSCPR04080'	, N'Sales Analysis By Product Aging-CSCPR04080'								, N'CSCPR04080', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 536	, N'CSCPR04090'	, N'Renew Analysis By Aging Report-CSCPR04090'								, N'CSCPR04090', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 537	, N'CSCPR05010'	, N'Product Information Report-CSCPR05010'									, N'CSCPR05010', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 538	, N'CSCPR05020'	, N'Job Details Information Report-CSCPR05020'								, N'CSCPR05020', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 539	, N'CSCPR05030'	, N'Job Analysis For Non-DCH Brand-CSCPR05030'								, N'CSCPR05030', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 540	, N'CSCPR05040'	, N'Repair Symptom Analysis Report (Defect Analysis Report)-CSCPR05040'		, N'CSCPR05040', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 541	, N'CSCPR05050'	, N'Technician Performance Report-CSCPR05050'								, N'CSCPR05050', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 542	, N'CSCPR05060'	, N'Technician Performance By Product Report-CSCPR05060'					, N'CSCPR05060', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 543	, N'CSCPR05070'	, N'District Distribution Report-CSCPR05070'								, N'CSCPR05070', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 544	, N'CSCPR05080'	, N'Model Information Report-CSCPR05080'									, N'CSCPR05080', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 545	, N'CSCPR05090'	, N'Accounting Movement Transaction Report-CSCPR05090'						, N'CSCPR05090', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 546	, N'CSCPR06010'	, N'Daily Sales Summary Report-CSCPR06010'									, N'CSCPR06010', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 547	, N'CSCPR06020'	, N'Inventory Distribution Report-CSCPR06020'								, N'CSCPR06020', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 548	, N'CSCPR06030'	, N'Posted Journals-CSCPR06030'												, N'CSCPR06030', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 549	, N'CSCPR06040'	, N'Parts Selling Price Audit Report-CSCPR06040'							, N'CSCPR06040', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 550	, N'CSCPR06050'	, N'Parts Selling Price Report-CSCPR06050'									, N'CSCPR06050', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 551	, N'CSCPR06060'	, N'Maintenance Price Report-CSCPR06060'									, N'CSCPR06060', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 552	, N'CSCPR06070'	, N'Maintenance Price Audit Report-CSCPR06070'								, N'CSCPR06070', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 553	, N'CSCPR06080'	, N'Product Information Audit Report-CSCPR06080'							, N'CSCPR06080', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 554	, N'CSCPR06090'	, N'AR Voucher Report-CSCPR06090'											, N'CSCPR06090', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 555	, N'CSCPR07010'	, N'Technician Incentive Bonus Report-CSCPR07010'							, N'CSCPR07010', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 556	, N'CSCPR07020'	, N'Customer Information Audit Report-CSCPR07020'							, N'CSCPR07020', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 557	, N'CSCPR07030'	, N'Parts Selling Price VS Cost Audit Report-CSCPR07030'					, N'CSCPR07030', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 558	, N'CSCPR07040'	, N'Stock Take Skip Parts Report-CSCPR07040'								, N'CSCPR07040', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 559	, N'CSCPR07050'	, N'Stock Arrival Report-CSCPR07050'										, N'CSCPR07050', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-05-16
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 39	, N'CSCS04010'	, N'Product Renewal Letter Printing-CSCS04010'						, N'CSCS04010', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 40	, N'CSCS04020'	, N'Rejoin Renewal Product Printing-CSCS04020'						, N'CSCS04020', N'N', N'CS',			@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-05-20
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 41	, N'CSCS04030'	, N'Take Order-CSCS04030'						, N'CSCS04030', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-05-27
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 42	, N'CSCP02070'	, N'PO Approval Setup-CSCP02070'			, N'CSCP02070', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-05-29
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 43	, N'CSCP02080'	, N'Assign Purchase Order Approval Rule-CSCP02080'	, N'CSCP02080', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 44	, N'CSCP02090'	, N'Stock Arrival Maintenance-CSCP02090'			, N'CSCP02090', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-05-31
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 45	, N'CSCP03010'	, N'Stock Transfer-CSCP03010'			, N'CSCP03010', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 46	, N'CSCP03020'	, N'Requisition Note-CSCP03020'			, N'CSCP03020', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-06-06
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 560	, N'CSCPR00010'	, N'Purchase Order-CSCPR00010'		, N'CSCPR00010', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 561	, N'CSCPR07070'	, N'Job Queue-CSCPR07070'			, N'CSCPR07070', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-06-07
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 47	, N'CSCS04040'	, N'Assign Job-CSCS04040'						, N'CSCS04040', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-06-08
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 48	, N'CSCS04050'	, N'Quotation-CSCS04050'						, N'CSCS04050', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 49	, N'CSCS04060'	, N'Enter Job Result and Complete-CSCS04060'	, N'CSCS04060', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-06-14
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		--SELECT 50	, N'CSCS04070'	, N'Holiday-CSCS04070'							, N'CSCS04070', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 51	, N'CSCP03030'	, N'Stock Adjustment-CSCP03030'					, N'CSCP03030', N'N', N'GODOWN',	@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 52	, N'CSCP03040'	, N'Sales Memo-CSCP03040'						, N'CSCP03040', N'N', N'GODOWN',	@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-06-21
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 50	, N'CSCP03050'	, N'Return To Vendor-CSCP03050'					, N'CSCP03050', N'N', N'GODOWN',	@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 53	, N'CSCP03060'	, N'Stock Arrival Correction-CSCP03060'			, N'CSCP03060', N'N', N'GODOWN',	@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-06-24
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 54	, N'CSCS04070'	, N'Print Job Sheet-CSCS04070'					, N'CSCS04070', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-06-25
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 55	, N'CSCP03070'	, N'Supplier Invoice-CSCP03070'					, N'CSCP03070', N'N', N'GODOWN',	@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-07-04
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 56	, N'CSCP03080'	, N'GL Account-CSCP03080'						, N'CSCP03080', N'N', N'GODOWN',	@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-07-09
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 57	, N'CSCS04080'	, N'Print Technician Daily Job List-CSCS04080'	, N'CSCS04080', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-07-15
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 58	, N'CSCP03090'	, N'Parts Enquiry-CSCP03090'							, N'CSCP03090', N'N', N'GODOWN',	@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 59	, N'CSCP04010'	, N'Technician Outstanding Parts Enquiry-CSCP04010'		, N'CSCP04010', N'N', N'GODOWN',	@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-07-18
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 60	, N'CSCP04020'	, N'Requisition Return-CSCP04020'		, N'CSCP04020', N'N', N'GODOWN',	@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;	
--add on 2013-07-24
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 61	, N'CSCS04090'	, N'Payment Method-CSCS04090'	, N'CSCS04090', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-07-25
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 62	, N'CSCS05010'	, N'Customer Invoice-CSCS05010'	, N'CSCS05010', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-07-31
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 63	, N'CSCP04030'	, N'Sales Return-CSCP04030'		, N'CSCP04030', N'N', N'GODOWN',	@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;	
--add on 2013-08-05
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 64	, N'CSCP04040'	, N'Stock Movement Enquiry-CSCP04040'		, N'CSCP04040', N'N', N'GODOWN',	@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE	UNION
		SELECT 65	, N'CSCP04050'	, N'Issued Requisition Enquiry-CSCP04050'	, N'CSCP04050', N'N', N'GODOWN',	@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE	UNION
		SELECT 66	, N'CSCP04060'	, N'Discontinue Parts Enquiry-CSCP04060'	, N'CSCP04060', N'N', N'GODOWN',	@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE	UNION
		SELECT 67	, N'CSCP04070'	, N'Parts Details Enquiry-CSCP04070'		, N'CSCP04070', N'N', N'GODOWN',	@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-08-15
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 68	, N'CSCS05020'	, N'Payment Terms-CSCS05020'	, N'CSCS05020', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-08-21
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 69	, N'CSCS05030'	, N'Adjust Job-CSCS05030'	, N'CSCS05030', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-08-22
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 70	, N'CSCS05040'	, N'Incentive Bonus-CSCS05040'	, N'CSCS05040', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-08-26
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 71	, N'CSCS05050'	, N'Job Payment-CSCS05050'	, N'CSCS05050', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 72	, N'CSCS05060'	, N'Generate Invoice/DR/CR Note-CSCS05060'	, N'CSCS05060', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-08-29
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 73	, N'CSCS05070'	, N'Product Upload-CSCS05070'	, N'CSCS05070', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-09-03
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 74	, N'CSCP04080'	, N'Stock Take-CSCP04080'	, N'CSCP04080', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 75	, N'CSCS05080'	, N'Discontinue Letter Printing-CSCS05080'	, N'CSCS05080', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 76	, N'CSCS05090'	, N'DR/CR Note-CSCS05090'	, N'CSCS05090', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-09-04
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 77	, N'CSCS06010'	, N'Payment Received-CSCS06010'	, N'CSCS06010', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 78	, N'CSCS06020'	, N'Bad Debt-CSCS06020'	, N'CSCS06020', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-09-09
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 79	, N'CSCS06030'	, N'Maintenance Policy Printout-CSCS06030'	, N'CSCS06030', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-09-11
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 80	, N'CSCS06040'	, N'Refund Maintenance Agreement-CSCS06040'	, N'CSCS06040', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-09-12
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 81	, N'CSCS06050'	, N'ID/OD Order-CSCS06050'	, N'CSCS06050', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 82	, N'CSCS06060'	, N'Settle Maintenance Renewal-CSCS06060'	, N'CSCS06060', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-09-14
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 562	, N'CSCPR07080'	, N'Daily Physical Stock OnHand Report -CSCPR07080'	, N'CSCPR07080', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 563	, N'CSCPR07090'	, N'Daily Job Allocation List-CSCPR07090'	, N'CSCPR07090', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 83	, N'CSCS06070'	, N'Print Invoice-CSCS06070'	, N'CSCS06070', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 84	, N'CSCS06080'	, N'Day End-CSCS06080'			, N'CSCS06080', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-09-25
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 85	, N'CSCS06090'	, N'Outstanding Job Enquiry-CSCS06090'		, N'CSCS06090', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 86	, N'CSCS07010'	, N'Job Waiting Parts Enquiry-CSCS07010'	, N'CSCS07010', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 87	, N'CSCS07020'	, N'Job Payment Enquiry-CSCS07020'			, N'CSCS07020', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-09-26
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 88	, N'CSCS07030'	, N'Job Important Field Approval-CSCS07030'	, N'CSCS07030', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-10-07
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 89	, N'CSCP04081'	, N'Stock Take Print Variant-CSCP04081'			, N'CSCP04081', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 90	, N'CSCP04082'	, N'Stock Take Print All-CSCP04082'				, N'CSCP04082', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 91	, N'CSCP04083'	, N'Stock Take Consolidate Report-CSCP04083'	, N'CSCP04083', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 92	, N'CSCP04084'	, N'Stock Take Discrepancy Report-CSCP04084'	, N'CSCP04084', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-11-19
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 93	, N'CSCS07040'	, N'Generate Invoice For Sales Memo-CSCS07040'	, N'CSCS07040', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-11-26
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 94	, N'CSCS07050'	, N'Job Payment Consolidate Report-CSCS07050'	, N'CSCS07050', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-11-27
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 95	, N'CSCS05031'	, N'Adjust Job Create Refund-CSCS05031'	, N'CSCS05031', N'N', N'CS',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-12-04
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 96	, N'CSCP04090'	, N'AP Charges-CSCP04090'					, N'CSCP04090', N'N', N'GODOWN',	@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2013-12-25
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 564	, N'CSCPR08010'	, N'User Role List Report-CSCPR08010'	, N'CSCPR08010', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE UNION
		SELECT 565	, N'CSCPR08020'	, N'Role Function List Report-CSCPR08020'	, N'CSCPR08020', N'N', N'GODOWN',		@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2014-01-22
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 97	, N'CSCS07060'	, N'Technician Group-CSCS07060'					, N'CSCS07060', N'N', N'CS',	@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2014-02-27
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 98	, N'CSCS07070'	, N'Upload EAD Product-CSCS07070'					, N'CSCS07070', N'N', N'CS',	@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
--add on 2014-03-26
INSERT SY_FUNCTION ([FUNC_ID], [FUNC_CODE], [DSC], [EXECUTABLE], [ADMIN_FLAG], [FUNC_TYPE], [SYSTEM_SCOPE], [SYS_CODE], [CREATED_BY], [CREATION_DATE], [LAST_UPDATED_BY], [LAST_UPDATE_DATE])
		SELECT 99	, N'CSCS07080'	, N'Override Job Result-CSCS07080'					, N'CSCS07080', N'N', N'CS',	@SYS_CODE, @SYS_CODE, @CUR_USER_ID, @CUR_DATE, @CUR_USER_ID, @CUR_DATE;
		