--/**********************************************************************/
---- Description:Shearch shop Godown
-----------------------------------------------------------------------
---- Action		Date			Staff		Version		Remarks
---- Create	 	2013-4-26   	zcs			1.00.00
-----------------------------------------------------------------------
--/**********************************************************************/

--CREATE PROCEDURE spShearchShopGodown
--(
--	@BU_CODE		NVarChar(20),
--	@SYS_CODE		NVarChar(8),
--	@ResultType     INT OUTPUT,
--	@ResultMessage NVARCHAR(1000) OUTPUT
--)
--AS
--BEGIN
--	SELECT 
--			* 
--    FROM 
--		   VW_GODOWN t where t.SYS_CODE=@SYS_CODE and t.BU_CODE=@BU_CODE

--SET @ResultType = 0;
--SET @ResultMessage = ''
--END